"""Public pure-domain contract for official paper-session settlement."""

from app.operational_paper_session_settlements.domain import (
    MAX_OPERATIONAL_PAPER_SESSION_SETTLEMENT_AMOUNT,
    MAX_OPERATIONAL_PAPER_SESSION_SETTLEMENT_IDEMPOTENCY_KEY_LENGTH,
    OPERATIONAL_PAPER_SESSION_SETTLEMENT_CONTRACT_VERSION,
    OPERATIONAL_PAPER_SESSION_SETTLEMENT_QUANTUM,
    OPERATIONAL_PAPER_SESSION_SETTLEMENT_SCHEMA_VERSION,
    OperationalPaperSessionSettlement,
    OperationalPaperSessionSettlementIntent,
    OperationalPaperSessionSettlementSpecification,
    build_operational_paper_session_settlement_specification,
    operational_paper_session_settlement_intent_fingerprint,
    operational_paper_session_settlement_specification_bytes,
    operational_paper_session_settlement_specification_checksum,
    operational_paper_session_settlement_specification_payload,
    operational_paper_session_settlement_specifications_equal,
    validate_operational_paper_session_settlement_idempotency_key,
    validate_operational_paper_session_settlement_specification_checksum,
)
from app.operational_paper_session_settlements.errors import (
    InvalidOperationalPaperSessionSettlementSpecificationError,
    OperationalPaperSessionAlreadySettledError,
    OperationalPaperSessionSettlementBoundsExceededError,
    OperationalPaperSessionSettlementChecksumMismatchError,
    OperationalPaperSessionSettlementEligibilityConflictError,
    OperationalPaperSessionSettlementIdempotencyConflictError,
    OperationalPaperSessionSettlementNotFoundError,
)

__all__ = [
    "InvalidOperationalPaperSessionSettlementSpecificationError",
    "MAX_OPERATIONAL_PAPER_SESSION_SETTLEMENT_AMOUNT",
    "MAX_OPERATIONAL_PAPER_SESSION_SETTLEMENT_IDEMPOTENCY_KEY_LENGTH",
    "OPERATIONAL_PAPER_SESSION_SETTLEMENT_CONTRACT_VERSION",
    "OPERATIONAL_PAPER_SESSION_SETTLEMENT_QUANTUM",
    "OPERATIONAL_PAPER_SESSION_SETTLEMENT_SCHEMA_VERSION",
    "OperationalPaperSessionAlreadySettledError",
    "OperationalPaperSessionSettlement",
    "OperationalPaperSessionSettlementBoundsExceededError",
    "OperationalPaperSessionSettlementChecksumMismatchError",
    "OperationalPaperSessionSettlementEligibilityConflictError",
    "OperationalPaperSessionSettlementIdempotencyConflictError",
    "OperationalPaperSessionSettlementIntent",
    "OperationalPaperSessionSettlementNotFoundError",
    "OperationalPaperSessionSettlementSpecification",
    "build_operational_paper_session_settlement_specification",
    "operational_paper_session_settlement_intent_fingerprint",
    "operational_paper_session_settlement_specification_bytes",
    "operational_paper_session_settlement_specification_checksum",
    "operational_paper_session_settlement_specification_payload",
    "operational_paper_session_settlement_specifications_equal",
    "validate_operational_paper_session_settlement_idempotency_key",
    "validate_operational_paper_session_settlement_specification_checksum",
]
