"""Versioned deterministic strategy-plugin framework."""

from app.strategies.builtins import (
    EmaCrossExamplePlugin,
    EmaCrossExamplePluginV2,
    EmaCrossExampleStrategy,
    NoOpStrategyPlugin,
    NoOpStrategyPluginV2,
)
from app.strategies.catalog import builtin_indicator_capabilities
from app.strategies.definitions import (
    StoredStrategyParameter,
    StrategyDefinition,
    StrategyDefinitionRepository,
    StrategyDefinitionService,
    StrategyDefinitionSpec,
    StrategyDefinitionState,
    StrategyParameterDocument,
    decode_strategy_parameters,
    encode_strategy_parameters,
    strategy_parameter_checksum,
    strategy_parameter_document_from_json,
    strategy_parameter_document_to_json,
)
from app.strategies.domain import (
    SUPPORTED_STRATEGY_LIFECYCLE_VERSIONS,
    SUPPORTED_STRATEGY_PLUGIN_SCHEMA_VERSIONS,
    IndicatorCapability,
    RawStrategyParameters,
    StrategyIndicatorRequirement,
    StrategyParameterKind,
    StrategyParameterSpec,
    StrategyPluginDescriptor,
)
from app.strategies.errors import (
    DuplicateStrategyPluginError,
    InvalidStrategyDefinitionError,
    InvalidStrategyPluginError,
    StrategyDefinitionArchivedError,
    StrategyDefinitionCompatibilityError,
    StrategyDefinitionConflictError,
    StrategyDefinitionNameConflictError,
    StrategyDefinitionNotFoundError,
    StrategyDefinitionRevisionConflictError,
    StrategyIndicatorCompatibilityError,
    StrategyParameterValidationError,
    StrategyPluginError,
    StrategyPluginNotFoundError,
    UnsupportedStrategyLifecycleError,
    UnsupportedStrategyPluginSchemaError,
)
from app.strategies.protocols import StrategyPlugin
from app.strategies.registry import StrategyPluginRegistry

__all__ = [
    "SUPPORTED_STRATEGY_LIFECYCLE_VERSIONS",
    "SUPPORTED_STRATEGY_PLUGIN_SCHEMA_VERSIONS",
    "DuplicateStrategyPluginError",
    "EmaCrossExamplePlugin",
    "EmaCrossExamplePluginV2",
    "EmaCrossExampleStrategy",
    "IndicatorCapability",
    "InvalidStrategyDefinitionError",
    "InvalidStrategyPluginError",
    "NoOpStrategyPlugin",
    "NoOpStrategyPluginV2",
    "RawStrategyParameters",
    "StrategyIndicatorCompatibilityError",
    "StrategyIndicatorRequirement",
    "StrategyParameterKind",
    "StrategyParameterSpec",
    "StrategyParameterValidationError",
    "StrategyPlugin",
    "StoredStrategyParameter",
    "StrategyDefinition",
    "StrategyDefinitionArchivedError",
    "StrategyDefinitionCompatibilityError",
    "StrategyDefinitionConflictError",
    "StrategyDefinitionNameConflictError",
    "StrategyDefinitionNotFoundError",
    "StrategyDefinitionRepository",
    "StrategyDefinitionRevisionConflictError",
    "StrategyDefinitionService",
    "StrategyDefinitionSpec",
    "StrategyDefinitionState",
    "StrategyParameterDocument",
    "StrategyPluginDescriptor",
    "StrategyPluginError",
    "StrategyPluginNotFoundError",
    "StrategyPluginRegistry",
    "UnsupportedStrategyLifecycleError",
    "UnsupportedStrategyPluginSchemaError",
    "builtin_indicator_capabilities",
    "decode_strategy_parameters",
    "encode_strategy_parameters",
    "strategy_parameter_checksum",
    "strategy_parameter_document_from_json",
    "strategy_parameter_document_to_json",
]
