"""Deterministic local backtesting contracts for ADT Phases 3A and 3B."""

from app.backtesting.artifacts import (
    BacktestArtifactStore,
    build_backtest_result,
    build_run_id,
)
from app.backtesting.comparison_batch import (
    BacktestComparisonBatch,
    ComparisonBatchGroup,
    ComparisonBatchGroupResult,
    ComparisonBatchRequest,
    build_comparison_batch,
    comparison_batch_request_from_mapping,
    load_comparison_batch_request,
)
from app.backtesting.domain import (
    SUPPORTED_STRATEGY_LIFECYCLE_VERSIONS,
    ArtifactChecksum,
    BacktestConfig,
    BacktestManifest,
    BacktestMetrics,
    BacktestResult,
    BacktestRunId,
    BacktestStatus,
    ClosedTrade,
    EquityPoint,
    EvaluationBacktestConfig,
    ExecutionAssumptions,
    FeeModel,
    Fill,
    FillLiquidity,
    FillReason,
    InstrumentConstraints,
    OrderIntent,
    OrderSide,
    OrderStatus,
    OrderType,
    PortfolioSnapshot,
    RiskLimits,
    SimulatedOrder,
    SlippageKind,
    SlippageModel,
    StrategyDescriptor,
    TimeInForce,
    strategy_lifecycle_version_for,
    validate_backtest_config,
)
from app.backtesting.engine import (
    BacktestExecutionResult,
    BacktestSnapshotReader,
    DeterministicBacktestEngine,
    LocalMarketSnapshotReader,
)
from app.backtesting.exports import (
    ComparisonExportManifest,
    ComparisonExportResult,
    ComparisonExportVerification,
    ComparisonReportExportStore,
    ComparisonReportExportVerifier,
    build_comparison_report_id,
    render_comparison_csv,
)
from app.backtesting.ledger import (
    BacktestLedger,
    LedgerEntry,
    LedgerEntryType,
    LedgerVerification,
    verify_ledger,
)
from app.backtesting.metrics import calculate_metrics, derive_closed_trades
from app.backtesting.portfolio import (
    PortfolioMutation,
    PortfolioState,
    apply_fill,
    initialize_portfolio,
    mark_to_market,
)
from app.backtesting.query import BacktestRunReader
from app.backtesting.registry import StrategyRegistration, StrategyRegistry
from app.backtesting.reports import (
    BacktestComparisonEntry,
    BacktestComparisonReport,
    ComparisonMetric,
    build_comparison_report,
    comparison_report_from_mapping,
)
from app.backtesting.risk import (
    DeterministicRiskManager,
    RiskDecision,
    RiskRejectionCode,
)
from app.backtesting.verifier import BacktestResultVerifier, BacktestVerification
from app.backtesting.visualization import (
    BacktestVisualization,
    BacktestVisualizationPoint,
    build_backtest_visualization,
)

__all__ = [
    "ArtifactChecksum",
    "BacktestArtifactStore",
    "BacktestComparisonBatch",
    "BacktestComparisonEntry",
    "BacktestComparisonReport",
    "BacktestConfig",
    "EvaluationBacktestConfig",
    "BacktestExecutionResult",
    "BacktestLedger",
    "BacktestManifest",
    "BacktestMetrics",
    "BacktestResult",
    "BacktestResultVerifier",
    "BacktestRunId",
    "BacktestRunReader",
    "BacktestSnapshotReader",
    "BacktestStatus",
    "BacktestVerification",
    "BacktestVisualization",
    "BacktestVisualizationPoint",
    "ClosedTrade",
    "ComparisonBatchGroup",
    "ComparisonBatchGroupResult",
    "ComparisonBatchRequest",
    "ComparisonMetric",
    "ComparisonExportManifest",
    "ComparisonExportResult",
    "ComparisonExportVerification",
    "ComparisonReportExportStore",
    "ComparisonReportExportVerifier",
    "DeterministicBacktestEngine",
    "DeterministicRiskManager",
    "EquityPoint",
    "ExecutionAssumptions",
    "FeeModel",
    "Fill",
    "FillLiquidity",
    "FillReason",
    "InstrumentConstraints",
    "LedgerEntry",
    "LedgerEntryType",
    "LedgerVerification",
    "LocalMarketSnapshotReader",
    "OrderIntent",
    "OrderSide",
    "OrderStatus",
    "OrderType",
    "PortfolioMutation",
    "PortfolioSnapshot",
    "PortfolioState",
    "RiskDecision",
    "RiskLimits",
    "RiskRejectionCode",
    "SUPPORTED_STRATEGY_LIFECYCLE_VERSIONS",
    "SimulatedOrder",
    "SlippageKind",
    "SlippageModel",
    "StrategyDescriptor",
    "StrategyRegistration",
    "StrategyRegistry",
    "TimeInForce",
    "apply_fill",
    "build_backtest_result",
    "build_backtest_visualization",
    "build_comparison_batch",
    "build_comparison_report",
    "build_comparison_report_id",
    "comparison_batch_request_from_mapping",
    "comparison_report_from_mapping",
    "load_comparison_batch_request",
    "render_comparison_csv",
    "build_run_id",
    "calculate_metrics",
    "derive_closed_trades",
    "initialize_portfolio",
    "mark_to_market",
    "strategy_lifecycle_version_for",
    "validate_backtest_config",
    "verify_ledger",
]
