"""Deterministic local backtesting contracts for ADT Phase 3A."""

from app.backtesting.artifacts import (
    BacktestArtifactStore,
    build_backtest_result,
    build_run_id,
)
from app.backtesting.domain import (
    ArtifactChecksum,
    BacktestConfig,
    BacktestManifest,
    BacktestMetrics,
    BacktestResult,
    BacktestRunId,
    BacktestStatus,
    ClosedTrade,
    EquityPoint,
    ExecutionAssumptions,
    FeeModel,
    Fill,
    FillLiquidity,
    FillReason,
    InstrumentConstraints,
    OrderIntent,
    OrderSide,
    OrderStatus,
    OrderType,
    PortfolioSnapshot,
    RiskLimits,
    SimulatedOrder,
    SlippageKind,
    SlippageModel,
    StrategyDescriptor,
    TimeInForce,
)
from app.backtesting.engine import (
    BacktestExecutionResult,
    BacktestSnapshotReader,
    DeterministicBacktestEngine,
    LocalMarketSnapshotReader,
)
from app.backtesting.ledger import (
    BacktestLedger,
    LedgerEntry,
    LedgerEntryType,
    LedgerVerification,
    verify_ledger,
)
from app.backtesting.metrics import calculate_metrics, derive_closed_trades
from app.backtesting.portfolio import (
    PortfolioMutation,
    PortfolioState,
    apply_fill,
    initialize_portfolio,
    mark_to_market,
)
from app.backtesting.query import BacktestRunReader
from app.backtesting.registry import StrategyRegistration, StrategyRegistry
from app.backtesting.risk import (
    DeterministicRiskManager,
    RiskDecision,
    RiskRejectionCode,
)
from app.backtesting.verifier import BacktestResultVerifier, BacktestVerification

__all__ = [
    "ArtifactChecksum",
    "BacktestArtifactStore",
    "BacktestConfig",
    "BacktestExecutionResult",
    "BacktestLedger",
    "BacktestManifest",
    "BacktestMetrics",
    "BacktestResult",
    "BacktestResultVerifier",
    "BacktestRunId",
    "BacktestRunReader",
    "BacktestSnapshotReader",
    "BacktestStatus",
    "BacktestVerification",
    "ClosedTrade",
    "DeterministicBacktestEngine",
    "DeterministicRiskManager",
    "EquityPoint",
    "ExecutionAssumptions",
    "FeeModel",
    "Fill",
    "FillLiquidity",
    "FillReason",
    "InstrumentConstraints",
    "LedgerEntry",
    "LedgerEntryType",
    "LedgerVerification",
    "LocalMarketSnapshotReader",
    "OrderIntent",
    "OrderSide",
    "OrderStatus",
    "OrderType",
    "PortfolioMutation",
    "PortfolioSnapshot",
    "PortfolioState",
    "RiskDecision",
    "RiskLimits",
    "RiskRejectionCode",
    "SimulatedOrder",
    "SlippageKind",
    "SlippageModel",
    "StrategyDescriptor",
    "StrategyRegistration",
    "StrategyRegistry",
    "TimeInForce",
    "apply_fill",
    "build_backtest_result",
    "build_run_id",
    "calculate_metrics",
    "derive_closed_trades",
    "initialize_portfolio",
    "mark_to_market",
    "verify_ledger",
]
