"""Public pure-domain contracts for operational paper-session activations."""

from app.operational_paper_session_activations.domain import (
    MAX_OPERATIONAL_PAPER_SESSION_ACTIVATION_IDEMPOTENCY_KEY_LENGTH,
    OPERATIONAL_PAPER_SESSION_ACTIVATION_CONTRACT_VERSION,
    OPERATIONAL_PAPER_SESSION_ACTIVATION_CREATE_CONTRACT_VERSION,
    OPERATIONAL_PAPER_SESSION_ACTIVATION_SCHEMA_VERSION,
    OperationalPaperSessionActivation,
    OperationalPaperSessionActivationCreateIntent,
    OperationalPaperSessionActivationSpecification,
    OperationalPaperSessionActivationState,
    authorize_operational_paper_session_activation,
    build_operational_paper_session_activation_specification,
    is_operational_paper_session_activation_transition_allowed,
    operational_paper_session_activation_create_intent_fingerprint,
    operational_paper_session_activation_specification_bytes,
    operational_paper_session_activation_specification_checksum,
    operational_paper_session_activation_specification_payload,
    operational_paper_session_activation_specifications_equal,
    require_operational_paper_session_activation_transition,
    revoke_operational_paper_session_activation,
    validate_operational_paper_session_activation_idempotency_key,
    validate_operational_paper_session_activation_specification_checksum,
)
from app.operational_paper_session_activations.errors import (
    InvalidOperationalPaperSessionActivationSpecificationError,
    OperationalPaperSessionActivationBoundsExceededError,
    OperationalPaperSessionActivationChecksumMismatchError,
    OperationalPaperSessionActivationCurrentGrantConflictError,
    OperationalPaperSessionActivationIdempotencyConflictError,
    OperationalPaperSessionActivationNotFoundError,
    OperationalPaperSessionActivationRecordVersionConflictError,
    OperationalPaperSessionActivationStateTransitionConflictError,
)

__all__ = [
    "MAX_OPERATIONAL_PAPER_SESSION_ACTIVATION_IDEMPOTENCY_KEY_LENGTH",
    "OPERATIONAL_PAPER_SESSION_ACTIVATION_CONTRACT_VERSION",
    "OPERATIONAL_PAPER_SESSION_ACTIVATION_CREATE_CONTRACT_VERSION",
    "OPERATIONAL_PAPER_SESSION_ACTIVATION_SCHEMA_VERSION",
    "InvalidOperationalPaperSessionActivationSpecificationError",
    "OperationalPaperSessionActivation",
    "OperationalPaperSessionActivationBoundsExceededError",
    "OperationalPaperSessionActivationChecksumMismatchError",
    "OperationalPaperSessionActivationCreateIntent",
    "OperationalPaperSessionActivationCurrentGrantConflictError",
    "OperationalPaperSessionActivationIdempotencyConflictError",
    "OperationalPaperSessionActivationNotFoundError",
    "OperationalPaperSessionActivationRecordVersionConflictError",
    "OperationalPaperSessionActivationSpecification",
    "OperationalPaperSessionActivationState",
    "OperationalPaperSessionActivationStateTransitionConflictError",
    "authorize_operational_paper_session_activation",
    "build_operational_paper_session_activation_specification",
    "is_operational_paper_session_activation_transition_allowed",
    "operational_paper_session_activation_create_intent_fingerprint",
    "operational_paper_session_activation_specification_bytes",
    "operational_paper_session_activation_specification_checksum",
    "operational_paper_session_activation_specification_payload",
    "operational_paper_session_activation_specifications_equal",
    "require_operational_paper_session_activation_transition",
    "revoke_operational_paper_session_activation",
    "validate_operational_paper_session_activation_idempotency_key",
    "validate_operational_paper_session_activation_specification_checksum",
]
