"""Public pure-domain contracts for operational paper-session materializations."""

from app.operational_paper_session_materializations.domain import (
    OPERATIONAL_PAPER_SESSION_MATERIALIZATION_CONTRACT_VERSION,
    OPERATIONAL_PAPER_SESSION_MATERIALIZATION_SCHEMA_VERSION,
    OperationalPaperSessionMaterialization,
    OperationalPaperSessionMaterializationAuthorizationBinding,
    OperationalPaperSessionMaterializationMandateBinding,
    OperationalPaperSessionMaterializationPlan,
    OperationalPaperSessionMaterializationProfileBinding,
    OperationalPaperSessionMaterializationSpecification,
    OperationalPaperSessionMaterializationState,
    build_operational_paper_session_materialization_plan,
    is_operational_paper_session_materialization_transition_allowed,
    materialize_operational_paper_session_materialization,
    operational_paper_session_materialization_specification_bytes,
    operational_paper_session_materialization_specification_checksum,
    operational_paper_session_materialization_specification_payload,
    operational_paper_session_materialization_specifications_equal,
    prepare_operational_paper_session_materialization,
    require_operational_paper_session_materialization_transition,
    validate_operational_paper_session_materialization_specification_checksum,
)
from app.operational_paper_session_materializations.errors import (
    InvalidOperationalPaperSessionMaterializationSpecificationError,
    OperationalPaperSessionMaterializationBoundsExceededError,
    OperationalPaperSessionMaterializationChecksumMismatchError,
    OperationalPaperSessionMaterializationConfigIdentityConflictError,
    OperationalPaperSessionMaterializationNotFoundError,
    OperationalPaperSessionMaterializationProfileBindingConflictError,
    OperationalPaperSessionMaterializationQuoteAssetConflictError,
    OperationalPaperSessionMaterializationStateTransitionConflictError,
)

__all__ = [
    "OPERATIONAL_PAPER_SESSION_MATERIALIZATION_CONTRACT_VERSION",
    "OPERATIONAL_PAPER_SESSION_MATERIALIZATION_SCHEMA_VERSION",
    "InvalidOperationalPaperSessionMaterializationSpecificationError",
    "OperationalPaperSessionMaterialization",
    "OperationalPaperSessionMaterializationAuthorizationBinding",
    "OperationalPaperSessionMaterializationBoundsExceededError",
    "OperationalPaperSessionMaterializationChecksumMismatchError",
    "OperationalPaperSessionMaterializationConfigIdentityConflictError",
    "OperationalPaperSessionMaterializationMandateBinding",
    "OperationalPaperSessionMaterializationNotFoundError",
    "OperationalPaperSessionMaterializationPlan",
    "OperationalPaperSessionMaterializationProfileBinding",
    "OperationalPaperSessionMaterializationProfileBindingConflictError",
    "OperationalPaperSessionMaterializationQuoteAssetConflictError",
    "OperationalPaperSessionMaterializationSpecification",
    "OperationalPaperSessionMaterializationState",
    "OperationalPaperSessionMaterializationStateTransitionConflictError",
    "build_operational_paper_session_materialization_plan",
    "is_operational_paper_session_materialization_transition_allowed",
    "materialize_operational_paper_session_materialization",
    "operational_paper_session_materialization_specification_bytes",
    "operational_paper_session_materialization_specification_checksum",
    "operational_paper_session_materialization_specification_payload",
    "operational_paper_session_materialization_specifications_equal",
    "prepare_operational_paper_session_materialization",
    "require_operational_paper_session_materialization_transition",
    "validate_operational_paper_session_materialization_specification_checksum",
]
