/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type OpenApiJsonValue =
    | null
    | boolean
    | number
    | string
    | OpenApiJsonValue[]
    | { [key: string]: OpenApiJsonValue };

export interface paths {
    "/api/v1/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Admin Me
         * @description Return the verified database-authorized administrator identity.
         */
        get: operations["get_admin_me_api_v1_admin_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Settings
         * @description List every non-secret application setting.
         */
        get: operations["list_settings_api_v1_admin_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Setting
         * @description Change only an existing setting value and record the administrator UUID.
         */
        patch: operations["update_setting_api_v1_admin_settings__key__patch"];
        trace?: never;
    };
    "/api/v1/admin/simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Simulations
         * @description List simulations newest first using bounded page pagination.
         */
        get: operations["list_simulations_api_v1_admin_simulations_get"];
        put?: never;
        /**
         * Create Simulation
         * @description Create the ACTIVE simulation and INITIAL_CAPITAL in one transaction.
         */
        post: operations["create_simulation_api_v1_admin_simulations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/simulations/{simulation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Simulation
         * @description Return one simulation with authoritative ledger totals.
         */
        get: operations["get_simulation_api_v1_admin_simulations__simulation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/simulations/{simulation_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Simulation
         * @description Transition an ACTIVE simulation to CANCELLED exactly once.
         */
        post: operations["cancel_simulation_api_v1_admin_simulations__simulation_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/simulations/{simulation_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Simulation
         * @description Transition an ACTIVE simulation to COMPLETED exactly once.
         */
        post: operations["complete_simulation_api_v1_admin_simulations__simulation_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/simulations/{simulation_id}/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Movements
         * @description List immutable movements in stable chronological order.
         */
        get: operations["list_movements_api_v1_admin_simulations__simulation_id__movements_get"];
        put?: never;
        /**
         * Create Movement
         * @description Append one allowed administrative movement; never rewrite the ledger.
         */
        post: operations["create_movement_api_v1_admin_simulations__simulation_id__movements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/simulation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Public Simulation
         * @description Return the UUID-free active simulation summary, when one exists.
         */
        get: operations["get_public_simulation_api_v1_public_simulation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Status
         * @description Get system status and configuration.
         */
        get: operations["get_status_api_v1_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Get API health status.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/database": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Database Health
         * @description Verify PostgreSQL without returning connection information.
         */
        get: operations["database_health_health_database_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Report readiness only when the required database is available.
         */
        get: operations["readiness_health_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminMeResponse
         * @description Authenticated administrator identity without email or token data.
         */
        AdminMeResponse: {
            /**
             * Is Admin
             * @default true
             */
            is_admin: boolean;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * CapitalMovementResponse
         * @description Immutable movement returned from the simulation ledger.
         */
        CapitalMovementResponse: {
            /** Amount */
            amount: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Metadata */
            metadata?: {
                [key: string]: components["schemas"]["JsonValue-Output"];
            } | null;
            /** Reason */
            reason: string;
            /** Reference Id */
            reference_id: string | null;
            /**
             * Simulation Id
             * Format: uuid
             */
            simulation_id: string;
            type: components["schemas"]["CapitalMovementType"];
        };
        /**
         * CapitalMovementType
         * @description Complete set of historical movement kinds stored in PostgreSQL.
         * @enum {string}
         */
        CapitalMovementType: "INITIAL_CAPITAL" | "ADMIN_DEPOSIT" | "ADMIN_WITHDRAWAL" | "TRADE_PROFIT" | "TRADE_LOSS" | "FEE" | "ADJUSTMENT";
        /**
         * ErrorPayload
         * @description Machine-readable error nested inside the standard envelope.
         */
        ErrorPayload: {
            /** Code */
            code: string;
            details?: components["schemas"]["JsonValue-Output"] | null;
            /** Message */
            message: string;
        };
        /**
         * ErrorResponse
         * @description Envelope returned for every handled API failure.
         */
        ErrorResponse: {
            error: components["schemas"]["ErrorPayload"];
        };
        /**
         * HealthResponse
         * @description A narrow health response with no infrastructure details.
         */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "healthy" | "ready";
        };
        "JsonValue-Input": OpenApiJsonValue;
        "JsonValue-Output": OpenApiJsonValue;
        /**
         * MovementCreateRequest
         * @description Append-only administrative ledger entry.
         */
        MovementCreateRequest: {
            /** Amount */
            amount: string;
            /** Metadata */
            metadata?: {
                [key: string]: components["schemas"]["JsonValue-Input"];
            } | null;
            /** Reason */
            reason: string;
            type: components["schemas"]["MovementCreateType"];
        };
        /**
         * MovementCreateType
         * @description Only movement kinds that an administrator may submit through the API.
         * @enum {string}
         */
        MovementCreateType: "DEPOSIT" | "WITHDRAWAL" | "ADJUSTMENT";
        /**
         * MovementListResponse
         * @description Chronological, paginated capital-movement history.
         */
        MovementListResponse: {
            /** Items */
            items: components["schemas"]["CapitalMovementResponse"][];
            pagination: components["schemas"]["PageMeta"];
        };
        /**
         * PageMeta
         * @description Metadata needed by clients to navigate a result set.
         */
        PageMeta: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * PublicSimulationSummaryResponse
         * @description Active simulation summary without UUID or administrator identifiers.
         */
        PublicSimulationSummaryResponse: {
            /** Currency */
            currency: string;
            /** Current Balance */
            current_balance: string;
            /** Initial Capital */
            initial_capital: string;
            /** Name */
            name: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @constant
             */
            status: "ACTIVE";
            /** Total Profit Loss */
            total_profit_loss: string;
        };
        /**
         * SettingPatchRequest
         * @description Only a setting's JSON value is mutable through the API.
         */
        SettingPatchRequest: {
            value: components["schemas"]["JsonValue-Input"];
        };
        /**
         * SettingResponse
         * @description Non-secret system setting visible to an administrator.
         */
        SettingResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /** Is Public */
            is_public: boolean;
            /** Key */
            key: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Updated By */
            updated_by: string | null;
            value: components["schemas"]["JsonValue-Output"];
        };
        /**
         * SettingsListResponse
         * @description Administrative setting collection.
         */
        SettingsListResponse: {
            /** Items */
            items: components["schemas"]["SettingResponse"][];
        };
        /**
         * SimulationCreateRequest
         * @description Fields accepted when opening a paper-trading simulation.
         */
        SimulationCreateRequest: {
            /** Currency */
            currency: string;
            /** Initial Capital */
            initial_capital: string;
            /** Name */
            name: string;
        };
        /**
         * SimulationDetailResponse
         * @description Simulation history plus calculated ledger totals.
         */
        SimulationDetailResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /** Currency */
            currency: string;
            /** Current Balance */
            current_balance: string;
            /** Ended At */
            ended_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Initial Capital */
            initial_capital: string;
            /** Name */
            name: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["SimulationStatus"];
            /** Total Profit Loss */
            total_profit_loss: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SimulationListItem
         * @description One simulation in the administrative history.
         */
        SimulationListItem: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Currency */
            currency: string;
            /** Current Balance */
            current_balance: string;
            /** Ended At */
            ended_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Initial Capital */
            initial_capital: string;
            /** Name */
            name: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["SimulationStatus"];
            /** Total Profit Loss */
            total_profit_loss: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SimulationListResponse
         * @description Paginated simulations ordered by the route's repository query.
         */
        SimulationListResponse: {
            /** Items */
            items: components["schemas"]["SimulationListItem"][];
            pagination: components["schemas"]["PageMeta"];
        };
        /**
         * SimulationStatus
         * @description States enforced by ``simulation_runs`` constraints.
         * @enum {string}
         */
        SimulationStatus: "ACTIVE" | "COMPLETED" | "CANCELLED";
        /**
         * SystemStatus
         * @description Narrow operational metadata with no infrastructure details.
         */
        SystemStatus: {
            /**
             * Environment
             * @enum {string}
             */
            environment: "development" | "test" | "staging" | "production";
            /**
             * Status
             * @constant
             */
            status: "operational";
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_admin_me_api_v1_admin_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMeResponse"];
                };
            };
            /** @description Malformed administrative request. */
            400: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication is missing or invalid. */
            401: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The authenticated user is not an administrator. */
            403: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested resource does not exist. */
            404: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested state change is not allowed. */
            409: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body exceeds the application limit. */
            413: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request does not satisfy the declared contract. */
            422: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected failure was safely normalized. */
            500: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A required service is temporarily unavailable. */
            503: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_settings_api_v1_admin_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsListResponse"];
                };
            };
            /** @description Malformed administrative request. */
            400: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication is missing or invalid. */
            401: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The authenticated user is not an administrator. */
            403: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested resource does not exist. */
            404: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested state change is not allowed. */
            409: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body exceeds the application limit. */
            413: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request does not satisfy the declared contract. */
            422: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected failure was safely normalized. */
            500: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A required service is temporarily unavailable. */
            503: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_setting_api_v1_admin_settings__key__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingResponse"];
                };
            };
            /** @description Malformed administrative request. */
            400: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication is missing or invalid. */
            401: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The authenticated user is not an administrator. */
            403: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested resource does not exist. */
            404: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested state change is not allowed. */
            409: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body exceeds the application limit. */
            413: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request does not satisfy the declared contract. */
            422: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected failure was safely normalized. */
            500: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A required service is temporarily unavailable. */
            503: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_simulations_api_v1_admin_simulations_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationListResponse"];
                };
            };
            /** @description Malformed administrative request. */
            400: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication is missing or invalid. */
            401: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The authenticated user is not an administrator. */
            403: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested resource does not exist. */
            404: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested state change is not allowed. */
            409: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body exceeds the application limit. */
            413: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request does not satisfy the declared contract. */
            422: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected failure was safely normalized. */
            500: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A required service is temporarily unavailable. */
            503: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_simulation_api_v1_admin_simulations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationDetailResponse"];
                };
            };
            /** @description Malformed administrative request. */
            400: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication is missing or invalid. */
            401: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The authenticated user is not an administrator. */
            403: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested resource does not exist. */
            404: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested state change is not allowed. */
            409: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body exceeds the application limit. */
            413: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request does not satisfy the declared contract. */
            422: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected failure was safely normalized. */
            500: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A required service is temporarily unavailable. */
            503: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_simulation_api_v1_admin_simulations__simulation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                simulation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationDetailResponse"];
                };
            };
            /** @description Malformed administrative request. */
            400: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication is missing or invalid. */
            401: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The authenticated user is not an administrator. */
            403: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested resource does not exist. */
            404: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested state change is not allowed. */
            409: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body exceeds the application limit. */
            413: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request does not satisfy the declared contract. */
            422: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected failure was safely normalized. */
            500: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A required service is temporarily unavailable. */
            503: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancel_simulation_api_v1_admin_simulations__simulation_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                simulation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationDetailResponse"];
                };
            };
            /** @description Malformed administrative request. */
            400: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication is missing or invalid. */
            401: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The authenticated user is not an administrator. */
            403: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested resource does not exist. */
            404: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested state change is not allowed. */
            409: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body exceeds the application limit. */
            413: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request does not satisfy the declared contract. */
            422: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected failure was safely normalized. */
            500: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A required service is temporarily unavailable. */
            503: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    complete_simulation_api_v1_admin_simulations__simulation_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                simulation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationDetailResponse"];
                };
            };
            /** @description Malformed administrative request. */
            400: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication is missing or invalid. */
            401: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The authenticated user is not an administrator. */
            403: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested resource does not exist. */
            404: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested state change is not allowed. */
            409: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body exceeds the application limit. */
            413: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request does not satisfy the declared contract. */
            422: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected failure was safely normalized. */
            500: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A required service is temporarily unavailable. */
            503: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_movements_api_v1_admin_simulations__simulation_id__movements_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                simulation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementListResponse"];
                };
            };
            /** @description Malformed administrative request. */
            400: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication is missing or invalid. */
            401: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The authenticated user is not an administrator. */
            403: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested resource does not exist. */
            404: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested state change is not allowed. */
            409: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body exceeds the application limit. */
            413: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request does not satisfy the declared contract. */
            422: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected failure was safely normalized. */
            500: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A required service is temporarily unavailable. */
            503: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_movement_api_v1_admin_simulations__simulation_id__movements_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                simulation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovementCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapitalMovementResponse"];
                };
            };
            /** @description Malformed administrative request. */
            400: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication is missing or invalid. */
            401: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The authenticated user is not an administrator. */
            403: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested resource does not exist. */
            404: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The requested state change is not allowed. */
            409: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body exceeds the application limit. */
            413: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request does not satisfy the declared contract. */
            422: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An unexpected failure was safely normalized. */
            500: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A required service is temporarily unavailable. */
            503: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_public_simulation_api_v1_public_simulation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicSimulationSummaryResponse"] | null;
                };
            };
            /** @description An unexpected failure was safely normalized. */
            500: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The database is temporarily unavailable. */
            503: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_status_api_v1_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
            /** @description An unexpected failure was safely normalized. */
            500: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The database is temporarily unavailable. */
            503: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description An unexpected failure was safely normalized. */
            500: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The database is temporarily unavailable. */
            503: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    database_health_health_database_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description An unexpected failure was safely normalized. */
            500: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The database is temporarily unavailable. */
            503: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    readiness_health_readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description An unexpected failure was safely normalized. */
            500: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The database is temporarily unavailable. */
            503: {
                headers: {
                    /** @description UUID correlation identifier assigned to this request. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
