"""Public pure-domain contracts for official operational paper-capital eras."""

from app.operational_paper_capital_eras.domain import (
    MAX_OPERATIONAL_PAPER_CAPITAL_ERA_IDEMPOTENCY_KEY_LENGTH,
    MAX_OPERATIONAL_PAPER_CAPITAL_ERA_INITIAL_CAPITAL,
    OPERATIONAL_PAPER_CAPITAL_ERA_DESIGNATION_CONTRACT_VERSION,
    OPERATIONAL_PAPER_CAPITAL_ERA_QUANTUM,
    OPERATIONAL_PAPER_CAPITAL_ERA_SCHEMA_VERSION,
    OperationalPaperCapitalEra,
    OperationalPaperCapitalEraDesignationIntent,
    OperationalPaperCapitalEraSpecification,
    build_operational_paper_capital_era_specification,
    operational_paper_capital_era_designation_intent_fingerprint,
    operational_paper_capital_era_specification_bytes,
    operational_paper_capital_era_specification_checksum,
    operational_paper_capital_era_specification_payload,
    operational_paper_capital_era_specifications_equal,
    validate_operational_paper_capital_era_idempotency_key,
    validate_operational_paper_capital_era_specification_checksum,
)
from app.operational_paper_capital_eras.errors import (
    InvalidOperationalPaperCapitalEraSpecificationError,
    OperationalPaperCapitalEraActiveConflictError,
    OperationalPaperCapitalEraBoundsExceededError,
    OperationalPaperCapitalEraChecksumMismatchError,
    OperationalPaperCapitalEraEligibilityConflictError,
    OperationalPaperCapitalEraIdempotencyConflictError,
    OperationalPaperCapitalEraNotFoundError,
    OperationalPaperCapitalEraSimulationAlreadyDesignatedError,
)

__all__ = [
    "MAX_OPERATIONAL_PAPER_CAPITAL_ERA_IDEMPOTENCY_KEY_LENGTH",
    "MAX_OPERATIONAL_PAPER_CAPITAL_ERA_INITIAL_CAPITAL",
    "OPERATIONAL_PAPER_CAPITAL_ERA_DESIGNATION_CONTRACT_VERSION",
    "OPERATIONAL_PAPER_CAPITAL_ERA_QUANTUM",
    "OPERATIONAL_PAPER_CAPITAL_ERA_SCHEMA_VERSION",
    "InvalidOperationalPaperCapitalEraSpecificationError",
    "OperationalPaperCapitalEra",
    "OperationalPaperCapitalEraActiveConflictError",
    "OperationalPaperCapitalEraBoundsExceededError",
    "OperationalPaperCapitalEraChecksumMismatchError",
    "OperationalPaperCapitalEraDesignationIntent",
    "OperationalPaperCapitalEraEligibilityConflictError",
    "OperationalPaperCapitalEraIdempotencyConflictError",
    "OperationalPaperCapitalEraNotFoundError",
    "OperationalPaperCapitalEraSimulationAlreadyDesignatedError",
    "OperationalPaperCapitalEraSpecification",
    "build_operational_paper_capital_era_specification",
    "operational_paper_capital_era_designation_intent_fingerprint",
    "operational_paper_capital_era_specification_bytes",
    "operational_paper_capital_era_specification_checksum",
    "operational_paper_capital_era_specification_payload",
    "operational_paper_capital_era_specifications_equal",
    "validate_operational_paper_capital_era_idempotency_key",
    "validate_operational_paper_capital_era_specification_checksum",
]
